apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chairmanmao
  namespace: chairmanmao
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chairmanmao
            port:
              number: 8002
