version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  lint-and-test:
    # These next lines defines a Docker executors: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of the convenience images from CircleCI's Developer Hub
    # A list of available CircleCI Docker convenience images are available here: https://circleci.com/developer/images/image/cimg/python
    # The executor is the environment in which the steps below will be executed - below will use a python 3.8 container
    # Change the version below to your required version of python
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout

      - run:
          name: Run CI script
          command: bash scripts/run-ci.sh

  build-containers:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker Login
          command: docker login -u $CONTAINER_REGISTRY_USERNAME -p $CONTAINER_REGISTRY_PASSWORD $CONTAINER_REGISTRY

      - run:
          name: Docker Build dmt-dailymandarinthreadinfo
          command: |
            docker build \
                -t $CONTAINER_REGISTRY/dmt-dailymandarinthreadinfo:latest \
                -t $CONTAINER_REGISTRY/dmt-dailymandarinthreadinfo:$CIRCLE_SHA1 \
                -f dmt_dailymandarinthreadinfo/Dockerfile \
                dmt_dailymandarinthreadinfo

      - run:
          name: Docker Build dmt-auth
          command: |
            docker build \
                -t $CONTAINER_REGISTRY/dmt-auth:latest \
                -t $CONTAINER_REGISTRY/dmt-auth:$CIRCLE_SHA1 \
                -f dmt_auth/Dockerfile \
                dmt_auth

      - run:
          name: Docker Build dmt-chairmanmao
          command: |
            docker build \
                -t $CONTAINER_REGISTRY/dmt-chairmanmao:latest \
                -t $CONTAINER_REGISTRY/dmt-chairmanmao:$CIRCLE_SHA1 \
                -f dmt_chairmanmao/Dockerfile \
                dmt_chairmanmao

      - run:
          name: Docker Build dmt-graphql
          command: |
            docker build \
                -t $CONTAINER_REGISTRY/dmt-graphql:latest \
                -t $CONTAINER_REGISTRY/dmt-graphql:$CIRCLE_SHA1 \
                -f dmt_graphql/Dockerfile \
                dmt_graphql

      - run:
          name: Docker Push dmt-chairmanmao
          command: |
            docker push $CONTAINER_REGISTRY/dmt-chairmanmao:latest
            docker push $CONTAINER_REGISTRY/dmt-chairmanmao:$CIRCLE_SHA1

      - run:
          name: Docker Push dmt-graphql
          command: |
            docker push $CONTAINER_REGISTRY/dmt-graphql:latest
            docker push $CONTAINER_REGISTRY/dmt-graphql:$CIRCLE_SHA1

      - run:
          name: Docker Push dmt-auth
          command: |
            docker push $CONTAINER_REGISTRY/dmt-auth:latest
            docker push $CONTAINER_REGISTRY/dmt-auth:$CIRCLE_SHA1

      - run:
          name: Docker Push dmt-dailymandarinthreadinfo
          command: |
            docker push $CONTAINER_REGISTRY/dmt-dailymandarinthreadinfo:latest
            docker push $CONTAINER_REGISTRY/dmt-dailymandarinthreadinfo:$CIRCLE_SHA1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  flow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
        #      - lint-and-test:
        #          context: DailyMandarinThread
      - build-containers:
          context: DailyMandarinThread
          #          requires:
          #            - lint-and-test
          filters:
            branches:
              only:
                - master
